### ISSUE TITLE
About pseudopotentials

### ISSUE THREAD

**Issue by raulguerrerofis** [siesta-project/tutorials#3]
Dear all,

I have a question about the pseudopotential files. There is a way to put the *psf files in a general directory so the SIESTA input can read them without do copies for many similar systems?

All the best,
Raúl Guerrero

**Comment by zerothi** [comment]
In 5.0 and later there is an environment variable:

 - `SIESTA_PS_PATH`

check the manual for its usage. :)

**Comment by raulguerrerofis** [comment]
Thank you a lot Nick ;)( I am using the 4.1.5, lucky me jajaj)

**Comment by zerothi** [comment]
Then there is no way.. :(
